# Generated by Django 4.2.13 on 2024-06-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosCaos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='UsuariosCaosNews',
        ),
    ]
